tittle: Duli Vazquez
logo: Duli195/DuliVazquez.github.io/blob/main/WhatsApp%20Image%202025-09-09%20at%204.03.19%20PM.jpeg/headshot_circle.png
#description: text
#show_downloads: true
theme: jekyll-theme-minimal
